# Generated by Django 3.2 on 2021-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
