# Generated by Django 3.2 on 2021-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210410_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
