# Generated by Django 3.2 on 2021-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210410_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
