# Generated by Django 3.2 on 2021-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0005_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='nombrearchivo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='referencia_imagen',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='referencia_media',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='referencia_texto',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='tipoarchivo',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
